[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8080

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Proxy API requests to backend
[[redirects]]
  from = "/api/*"
  to = "https://api.niche-market-canvas.com/:splat"
  status = 200
  force = true
