"""Add default_commission_rate to seller_profiles

Revision ID: a45b0ddb8b8f
Revises: f0b9db91d3ee
Create Date: 2025-07-08 20:21:23.871435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45b0ddb8b8f'
down_revision = 'f0b9db91d3ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_commission_rate', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_profiles', schema=None) as batch_op:
        batch_op.drop_column('default_commission_rate')

    # ### end Alembic commands ###
