"""Synchronize all model inconsistencies

Revision ID: a52b15f3a351
Revises: a45b0ddb8b8f
Create Date: 2025-07-08 21:39:57.711365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a52b15f3a351'
down_revision = 'a45b0ddb8b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('niche', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_profiles', schema=None) as batch_op:
        batch_op.drop_column('niche')

    # ### end Alembic commands ###
